Support WIF in examples workflows
google-github-actions/setup-gcloud pull request #428
Opened 2021-12-08 10:56 UTC by FrodoTheTrue

2021-12-08 13:42 UTC, sethvargo approved these changes

2021-12-08 16:23 UTC, bharathkkb commented on example-workflows/cloud-build/.github/workflows/cloud-build.yml
> +      uses: 'google-github-actions/auth@v0.4.0'
```suggestion
      uses: 'google-github-actions/auth@v0.4.1'
```

2021-12-08 16:23 UTC, bharathkkb commented on example-workflows/cloud-build/.github/workflows/cloud-build.yml
> +        token_format: 'access_token'
I don't think we need to create an access token, setup-gcloud picks up just the WIF creds file.

2021-12-15 15:50 UTC, sethvargo requested changes

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/cloud-build/.github/workflows/cloud-build.yml
> +      uses: 'google-github-actions/auth@v0.4.0'
Can you pin to `@v0` instead?

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/cloud-build/.github/workflows/cloud-build.yml
> +    #   uses: google-github-actions/auth@v0.4.0
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/cloud-run/cloud-run.yml
> +      uses: 'google-github-actions/auth@v0.4.0'
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/cloud-run/cloud-run.yml
> +        token_format: 'access_token'
Not needed

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gae/app-engine.yml
> +        uses: 'google-github-actions/auth@v0.4.0'
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gae/app-engine.yml
> +          token_format: 'access_token'
Not needed

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gce/.github/workflows/gce.yaml
> +      uses: 'google-github-actions/auth@v0.4.0'
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gce/.github/workflows/gce.yaml
> +        token_format: 'access_token'
Not needed

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gce/.github/workflows/gce.yaml
> +    #   uses: google-github-actions/auth@v0.4.0
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gae/app-engine.yml
> +      #   uses: google-github-actions/auth@v0.4.0
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gke-kustomize/.github/workflows/gke-kustomize.yml
> +permissions:
It'd be better to put this inside the specific job that needs it, that way it's not exposed in all jobs.

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gke-kustomize/.github/workflows/gke-kustomize.yml
> +      uses: 'google-github-actions/auth@v0.4.0'
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gke-kustomize/.github/workflows/gke-kustomize.yml
> +    #   uses: google-github-actions/auth@v0.4.0
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gke-kustomize/.github/workflows/gke-kustomize.yml
> +        token_format: 'access_token'
Not needed

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gke/.github/workflows/gke.yml
> +      uses: 'google-github-actions/auth@v0.4.0'
`@v0`

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gke/.github/workflows/gke.yml
> +        token_format: 'access_token'
Not needed

2021-12-15 15:50 UTC, sethvargo commented on example-workflows/gke/.github/workflows/gke.yml
> +    #   uses: google-github-actions/auth@v0.4.0
`@v0`

2021-12-22 16:23 UTC, sethvargo requested changes

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/cloud-build/.github/workflows/cloud-build.yml
> +    # - id: auth
Please quote these (even though they are commented)

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/cloud-build/.github/workflows/cloud-build.yml
> +      uses: google-github-actions/setup-gcloud@v0.3.0
```suggestion
      uses: google-github-actions/setup-gcloud@v0
```

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/cloud-run/cloud-run.yml
> +    # Alternative option - authentication via credentials json
Please quote these (even though they are commented)

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/cloud-run/cloud-run.yml
> +      uses: 'google-github-actions/auth@@v0'
```suggestion
      uses: 'google-github-actions/auth@v0'
```

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/cloud-run/cloud-run.yml
> +      uses: google-github-actions/setup-gcloud@v0.3.0
```suggestion
      uses: google-github-actions/setup-gcloud@v0
```

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/gae/app-engine.yml
> +      # Alternative option - authentication via credentials json
Please quote these (even though they are commented)

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/gae/app-engine.yml
> +        uses: google-github-actions/setup-gcloud@v0.3.0
```suggestion
        uses: google-github-actions/setup-gcloud@v0
```

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/gce/.github/workflows/gce.yaml
> +    # Alternative option - authentication via credentials json
Please quote these (even though they are commented)

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/gce/.github/workflows/gce.yaml
> +      uses: google-github-actions/setup-gcloud@v0.3.0
```suggestion
      uses: google-github-actions/setup-gcloud@v0
```

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/gke-kustomize/.github/workflows/gke-kustomize.yml
> +    # Alternative option - authentication via credentials json
Please quote these (even though they are commented)

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/gke-kustomize/.github/workflows/gke-kustomize.yml
> +      uses: google-github-actions/setup-gcloud@v0.3.0
```suggestion
      uses: google-github-actions/setup-gcloud@v0
```

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/gke/.github/workflows/gke.yml
> +    # Alternative option - authentication via credentials json
Please quote these (even though they are commented)

2021-12-22 16:23 UTC, sethvargo commented on example-workflows/gke/.github/workflows/gke.yml
> +      uses: google-github-actions/setup-gcloud@v0.3.0
```suggestion
      uses: google-github-actions/setup-gcloud@v0
```

2021-12-22 16:48 UTC, sethvargo approved these changes

2021-12-22 16:56 UTC, FrodoTheTrue commented
Connected PR to starter-workflows: https://github.com/actions/starter-workflows/pull/1327/files

2021-12-22 17:09 UTC, merged